### ISSUE TITLE
the data of bundle adjustment

### ISSUE THREAD

**Issue by lf-191** [LulinZhang/SpS-NeRF#1]
how to get the sunangles.txt and the WGS84toUTM.xml from DFC2019

**Comment by LulinZhang** [comment]
Hi, the WGS84toUTM.xml is available here: 
https://drive.google.com/file/d/1Tc_W9B0u0UjdYqeEplQYKVnn-63P--qr/view?usp=sharing

**Comment by lf-191** [comment]
Thank you for your reply, but how to get sunangles data for images of DFC2019?

**Comment by LulinZhang** [comment]
Hi, the sunangles data for DFC2019 is available as JAX_214_sunangles.txt in DFC2019.zip here:
https://drive.google.com/file/d/1kVuEKONJamt1R9caxY-zJFVQXgbiQDsM/view?usp=sharing

**Comment by gogogo617** [comment]
您好，如果是其他数据，该如何获取sunangles 数据呢，谢谢

**Comment by LulinZhang** [comment]
> 您好，如果是其他数据，该如何获取sunangles 数据呢，谢谢

您好，sunangles在卫星影像元数据里

**Comment by gogogo617** [comment]
谢谢您的回复
