### ISSUE TITLE
MicMac dense generate error

### ISSUE THREAD

**Issue by ShiningFeng** [LulinZhang/SpS-NeRF#2]
When I followed the instructions you gave me for dense_generate with micmac, I encountered some problems. This problem occurs in the section # copy the images and refined rpc parameters in 1.2 of README. An error is reported after entering the instruction: Sorry, the following FATAL ERROR happy cRPC:: ReadASCII (const std:: string & aFile) ASCII file not found.
I hope you can give me some advice. I'm stuck in this step now. Thank you!

**Comment by ShiningFeng** [comment]
the error log: 
Exit with code 1 
Generated from line 202  of file D:\a\micmac\micmac\src\util\error.cpp 
PID=24188
Context=[cEliseFatalErrorHandler::cEFEH_OnErreur]
GMEC:mes=cRPC::ReadASCII(const std::string &aFile) ASCII file not found  line=3178 file=D:\a\micmac\micmac\src\uti_phgrm\Apero\cCameraRPC.cpp
MM3D-Command=["C:\micmac\bin\mm3d.exe" "Convert2GenBundle" "(.*).tif" "\.txt" "RPC-d0-adj" "ChSys=WGS84toUTM.xml" "Degre=0" ]

**Comment by LulinZhang** [comment]
Hi, it seems like MicMac couldn't find you RPC file, please check if you missed the "**\$1**" for the following command in section 1.2 of the README:
mm3d Convert2GenBundle "(.*).tif" "**\$1**.txt" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0

**Comment by ShiningFeng** [comment]
> Hi, it seems like MicMac couldn't find you RPC file, please check if you missed the "**$1**" for the following command in section 1.2 of the README: mm3d Convert2GenBundle "(.*).tif" "**$1**.txt" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0

I have tried command as follows:
mm3d Convert2GenBundle "(.*).tif" "\$1.txt" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0
mm3d Convert2GenBundle "(.*).tif" "$1.txt" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0
mm3d Convert2GenBundle "(.*).tif" "(.*).txt" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0
but no one works. 

Screenshots of files contained in the folder of the destination path are as follows:
![2024-01-25_11-33-05](https://github.com/LulinZhang/SpS-NeRF/assets/102225635/baa5d6dc-6a5e-4651-845d-9426fac906b2)
The RPC files are as folows:
![2024-01-25_11-33-33](https://github.com/LulinZhang/SpS-NeRF/assets/102225635/40f6f083-50db-48f5-9c0e-3714d849803c)

The error is as follows: 
![2024-01-25_11-52-58](https://github.com/LulinZhang/SpS-NeRF/assets/102225635/aae64f98-cf8c-4799-af46-f92411bf0e09)

By the way, I use MicMac in the Windows platform. 

 I'm really looking forword to your help, thanks !

**Comment by erupnik** [comment]
Hi, there is a „\„ missing in your command, that’s the correct version:
mm3d Convert2GenBundle "(.*).tif" "\$1.txt" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0

Cheers

**Comment by erupnik** [comment]
Github removes the special sign from the messages, for some bizarre reason. You should precede the dollar sign with „\” -> \ $

also, don’t forget to put the star character within the symbol definition „(.*).tif”

**Comment by LulinZhang** [comment]
Yes, the correct version is this one:
mm3d Convert2GenBundle "(.*).tif" "**\\$1.txt**" RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0

or, you can replace this command with the following 4 commands to avoid the complexity of the regular expression:
mm3d Convert2GenBundle JAX_214_007_RGB.tif JAX_214_007_RGB.txt RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0
mm3d Convert2GenBundle JAX_214_008_RGB.tif JAX_214_008_RGB.txt RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0
mm3d Convert2GenBundle JAX_214_009_RGB.tif JAX_214_009_RGB.txt RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0
mm3d Convert2GenBundle JAX_214_010_RGB.tif JAX_214_010_RGB.txt RPC-d0-adj ChSys=WGS84toUTM.xml Degre=0

**Comment by ShiningFeng** [comment]
Thank you for your answers!
I found the problem, WINDOSW POWERSHELL doesn't support full regular expressions. So '$1' can't be used. 
I follow the instructipn to specify files one by one, and complete the mm3d Convert2GenBundle function successfully.
But in the next step, I tried to execute mm3d Malt GeomImage and mm3d TestLib GeoreferencedDepthMap in the way specified one by one, but I still encountered problems that could not be solved.
![2024-01-29_17-24-12](https://github.com/LulinZhang/SpS-NeRF/assets/102225635/4ea59ccc-59c8-4af3-9e64-3ba8f1ed753b)

**Comment by LulinZhang** [comment]
Hi, thank you for pointing this out.
MicMac could not read the original JAX tif format of the training images, you need to convert the images before launching MicMac, by QGIS for example (with "raster -> conversion -> convert"), or you can download the [images we converted](https://drive.google.com/file/d/1Ki1p5CpAIpZPhohjwnUQiHiOdu5bOQAW/view?usp=sharing).

**Comment by ShiningFeng** [comment]
Thank you for your answer. I want to replicate all the pocedures so that I canapply my own data to the SpS-NeRF.

I just downloaded QGIS and followed your help ("raster -> conversion -> Translate(convert format"). I selected the file "JAX_214_009_RGB.tif", and I don't konw which advanced parameters I need to selected (Such as"Out put data type":). (I search the DocMiCMac, it tells the Tiff can be in 16 bits or 8 bits, in 1 or 3 channel)

**Comment by LulinZhang** [comment]
No advanced parameters are needed, just do the conversion without any parameter and it will work in MicMac.

**Comment by ShiningFeng** [comment]
Thank you very much for your help! I still need your help with one more question. In the last step, I tried the following instructions:

mm3d TestLib GeoreferencedDepthMap MM-"$img_name" "$img_name. tif" Ori-RPC-d0-adj OutDir= "$TxtDenseDir" Mask=1 Scale=4
mm3d TestLib GeoreferencedDepthMap MM-JAX_214_009_RGB JAX_214_009_RGB Ori-RPC-d0-adj OutDir= "$TxtDenseDir" Mask=1 Scale=4

But there is an error happened:
![2024-01-29_21-33-12](https://github.com/LulinZhang/SpS-NeRF/assets/102225635/d879dd55-2707-4328-8426-521a0191b8ef)

**Comment by LulinZhang** [comment]
Your MicMac didn't recognize the "GeoreferencedDepthMap" command, which is added into MicMac several months ago. Please try to update your MicMac and I think it will be OK.

**Comment by ShiningFeng** [comment]
My MicMac(Windows) is the latest version which is published on Mar 31, 2023 from the girhub homepage of MicMac. Can you tell me where are the newer releases. Thanks!

**Comment by LulinZhang** [comment]
The codes of MicMac evolves through time, you need to pull the codes and compile again.

**Comment by ShiningFeng** [comment]
All right... Before using Windows version, I try to compile it but failed in the pocedure of CMake...
