### ISSUE TITLE
About the satnerf eval results

### ISSUE THREAD

**Issue by WBS111** [LulinZhang/SpS-NeRF#3]
Hello and thank you for your wonderful work!
Here I have a question for you about satnerf. I ran the code published by satnerf and tested it using the pretrained model provided, and while PSNR and SSIM were able to achieve the results reported in the article, the MAE metrics, which measure the accuracy of the DSM, differed. 
I raised this issue in satnerf https://github.com/centreborelli/satnerf/issues/13 but the solution he provided did not solve the problem, even the MAE = 2.900m for the Sat-NeRF model on AOI214 but reported in the article is 2.125m.I would like to ask if there is such a problem in your environment?

**Comment by LulinZhang** [comment]
Hi, I didn't run into this kind of problem, because our research is aimed for sparse input views, I train satnerf use only 3 images for comparison.
