### ISSUE TITLE
About spsnerf train

### ISSUE THREAD

**Issue by HarryPeverell** [LulinZhang/SpS-NeRF#4]
I would like to express my sincere appreciation for the exceptional work you have done on your GitHub repository. Your contributions to the open-source community are truly commendable.

I am reaching out to you with a few queries that I have encountered while attempting to replicate your code.

1. During the training process, I came across a line of code that I am unable to execute: `cp Sh-SpS-Train-JAX_---_2imgs.sh "$Output"/.`. I am unsure about the nature of the file `Sh-SpS-Train-JAX_---_2imgs.sh`. Could you please provide some insight into what this script is and how it should be used?

2. Upon running the training, I encountered the following error messages:

```
LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5.
RequestsDependencyWarning: urllib3 (1.26.19) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
```

I understand that the `pytorch_lightning.metrics` module has been deprecated and renamed to `torchmetrics`. However, I am unsure about the necessary steps to update my code to avoid this deprecation warning. Could you please advise on how to resolve this issue?

I have attached the full log of the error for your reference. Your prompt response will be highly appreciated as it will help me to continue with my project.

Thank you very much for your time and assistance. I look forward to your valuable insights.

```plaintext
/home/harry/anaconda3/envs/spsnerf/lib/python3.6/site-packages/pytorch_lightning/metrics/__init__.py:44: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics)  since v1.3 and will be removed in v1.5
  "`pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package"
/home/harry/anaconda3/envs/spsnerf/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.19) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)

Running SpS_outputJAX_214-DenseDepth_ZM4-FnMd0-ds1-1 - Using gpu 0

--aoi_id:  JAX_214
--beta:  False
--sc_lambda:  0.0
--mapping:  True
--inputdds:  DenseDepth_ZM4
--ds_lambda:  1.0
--ds_drop:  1.0
--GNLL:  False
--usealldepth:  False
--guidedsample:  True
--margin:  0.0001
--stdscale:  1.0
--corrscale:  1
--model:  sps-nerf
--exp_name:  SpS_outputJAX_214-DenseDepth_ZM4-FnMd0-ds1-1
--lr:  0.0005
--n_samples:  64
--n_importance:  0
------------------------------
--root_dir:  /home/harry/SpS-NeRF/ProjDir/datasetJAX_214/root_dir/crops_rpcs_ba_v2/JAX_214/
--img_dir:  /home/harry/SpS-NeRF/ProjDir/datasetJAX_214/JAX_214/RGB-crops/JAX_214/
--ckpts_dir:  /home/harry/SpS-NeRF/ProjDir/SpS_outputJAX_214-DenseDepth_ZM4-FnMd0-ds1-1/ckpts
--logs_dir:  /home/harry/SpS-NeRF/ProjDir/SpS_outputJAX_214-DenseDepth_ZM4-FnMd0-ds1-1/logs
--gt_dir:  /home/harry/SpS-NeRF/ProjDir/datasetJAX_214/JAX_214/Truth
--cache_dir:  /home/harry/SpS-NeRF/ProjDir/SpS_outputJAX_214-DenseDepth_ZM4-FnMd0-ds1-1/cache_dir/crops_rpcs_ba_v2/JAX_214
--ckpt_path:  None
--gpu_id:  0
--batch_size:  1024
--img_downscale:  1.0
--max_train_steps:  30000
--save_every_n_epochs:  4
--fc_units:  512
--fc_layers:  8
--noise_std:  0.0
--chunk:  5120
--ds_noweights:  False
--first_beta_epoch:  2
--t_embbeding_tau:  4
--t_embbeding_vocab:  30
SatNeRF: layers, feat:  8 512
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
Load SatelliteRGBDEPDataset with corrscale:  1
/home/harry/SpS-NeRF/ProjDir/datasetJAX_214/root_dir/crops_rpcs_ba_v2/JAX_214//scene.loc already exist, hence skipped scaling
Image JAX_214_009_RGB loaded ( 1 / 2 )
Image JAX_214_010_RGB loaded ( 2 / 2 )
center, range:  tensor([  798962.7500, -5452430.5000,  3200708.5000]) tensor(159.)
Depth JAX_214_009_RGB loaded ( 1 / 2 )
depth range: [0.28295, 0.71207], mean: 0.59907
corr  range: [0.00000, 1.00000], mean: 0.93883
std   range: [0.00010, 1.00010], mean: 0.06127
74.27127 percent of pixels are valid in depth map.
段错误 (核心已转储)

```

**Comment by LulinZhang** [comment]
Hello, thank you for your interest into our work. To answer your questions:
1. cp Sh-SpS-Train-JAX_---_2imgs.sh "$Output"/. is just something I used for debugging, which I forgot to remove from the script. You can just ignore it.
2. The warning of pytorch_lightning is OK, I think you problem is caused when loading depth files. I updated the code and I think that should solve your problem.

**Comment by HarryPeverell** [comment]
> Hello, thank you for your interest into our work. To answer your questions:
> 
> 1. cp Sh-SpS-Train-JAX_---_2imgs.sh "$Output"/. is just something I used for debugging, which I forgot to remove from the script. You can just ignore it.
> 2. The warning of pytorch_lightning is OK, I think you problem is caused when loading depth files. I updated the code and I think that should solve your problem.

I wanted to extend my appreciation for your assistance. Your advice and expert guidance were pivotal in resolving the issues I was encountering, and I'm thrilled to report that as a result, the training process has been a complete success. The program is now running flawlessly.Thank you once again for your support.
