### ISSUE TITLE
RECONSTRUCT OTHER SCENES

### ISSUE THREAD

**Issue by gogogo617** [LulinZhang/SpS-NeRF#5]
HELLO, EXCUSE ME, THANKS FOR THE GREAT WORK, CAN I USE SPSNERF TO RECONSTRUCT OTHER SCENES

**Comment by LulinZhang** [comment]
Hi, thank you for your interest in our work. Yes you can generate your own dataset following this: https://github.com/LulinZhang/SpS-NeRF?tab=readme-ov-file#1-prepare-dataset

**Comment by gogogo617** [comment]
ok，thank you
